language: node_js
sudo: false
node_js:
- '4'
cache:
  apt: true
  directories:
  - node_modules
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  ssh_known_hosts: github.com
script:
- npm run build
deploy:
  provider: script
  script: sh .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_7ff604ad71d5_key -iv $encrypted_7ff604ad71d5_iv
  -in ssh_key.enc -out ~\/.ssh/ssh_key -d
