title: kuangjia.org
subtitle: "开发和运维"
description: "区块链运维和开发的数据服务, 金融, 游戏, 电商, 教育和营销产品的平台数据服务。"
author: Kuangjia Network
language: zh-cn
timezone: Asia/Shanghai
url: http://kuangjia.org
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: blockchain
deploy:
  type: git
  repo: git@github.com:boy12371/boy12371.github.io.git
  branch: master
  message: Site updated {{ now('YYYY-MM-DD HH:mm:ss') }}

disqus_shortname: kuangjia.org
google_analytics:
fb_admins:
algolia:
  zh-cn:
    api_key:
    index_name: kuangjia_zh-cn
  en:
    api_key:
    index_name: kuangjia
twitter: kuangjia
github: boy12371/boy12371.github.io
