title: kuangjia.org
subtitle: "开发和运维"
description: "互联网运维和开发的数据服务, 金融, 游戏, 营销和研发产品, 平台数据服务。"
author: Richard Kuang
language: zh-cn
timezone: Asia/Shanghai
url: http://boy12371.github.io
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:boy12371/boy12371.github.io.git

disqus_shortname: kuangjia.com
google_analytics:
fb_admins: 100000247608790
algolia:
  zh-cn:
    api_key:
    index_name: kuangjia_zh-cn
  en:
    api_key:
    index_name: kuangjia
twitter: kuangjia
github: boy12371/boy12371.github.io
